version: '3.9'

services:
  web:
    build: .
    container_name: ecom_webapp_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./static/images:/app/static/images
    restart: always
