version: '3.9'

services:
  web:
    build: .
    container_name: ecom_webapp_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app                     # Mount project folder
      - ./static/images:/app/static/images  # Persist uploaded images
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
